from typing import TypedDict


class WeekInfo(TypedDict):
    size: str
    length_cm: float
    weight_g: float
    development: str
    tips: str
    analyses: str
    checklist: list[str]


WEEKS_DATA: dict[int, WeekInfo] = {
    1: {
        "size": "Маковое зёрнышко",
        "length_cm": 0.01,
        "weight_g": 0,
        "development": "Начало цикла.",
        "tips": "Фолиевая кислота.",
        "analyses": "Гинеколог.",
        "checklist": ["Фолиевая кислота"],
    },
    2: {
        "size": "Маковое зёрнышко",
        "length_cm": 0.01,
        "weight_g": 0,
        "development": "Овуляция.",
        "tips": "ЗОЖ.",
        "analyses": "",
        "checklist": ["Овуляция"],
    },
    3: {
        "size": "Булавочная головка",
        "length_cm": 0.02,
        "weight_g": 0,
        "development": "Оплодотворение!",
        "tips": "Витамины.",
        "analyses": "",
        "checklist": ["Витамины"],
    },
    4: {
        "size": "Маковое зёрнышко",
        "length_cm": 0.1,
        "weight_g": 0,
        "development": "Имплантация.",
        "tips": "Тест.",
        "analyses": "ХГЧ.",
        "checklist": ["Тест", "ХГЧ"],
    },
    5: {
        "size": "Кунжут",
        "length_cm": 0.2,
        "weight_g": 0,
        "development": "Нервная трубка. Сердце бьётся.",
        "tips": "К врачу.",
        "analyses": "Постановка на учёт.",
        "checklist": ["Встать на учёт"],
    },
    6: {
        "size": "Чечевица",
        "length_cm": 0.5,
        "weight_g": 0.1,
        "development": "Зачатки рук и ног.",
        "tips": "Часто и понемногу.",
        "analyses": "УЗИ.",
        "checklist": ["Первое УЗИ"],
    },
    7: {
        "size": "Черника",
        "length_cm": 1.0,
        "weight_g": 0.5,
        "development": "Мозг развивается.",
        "tips": "Отдых.",
        "analyses": "",
        "checklist": ["Режим сна"],
    },
    8: {
        "size": "Малина",
        "length_cm": 1.6,
        "weight_g": 1.0,
        "development": "Все органы заложены.",
        "tips": "Крем от растяжек.",
        "analyses": "Анализы.",
        "checklist": ["Сдать анализы"],
    },
    9: {
        "size": "Вишня",
        "length_cm": 2.3,
        "weight_g": 2.0,
        "development": "Плод.",
        "tips": "Кальций.",
        "analyses": "",
        "checklist": ["Кальций"],
    },
    10: {
        "size": "Клубника",
        "length_cm": 3.1,
        "weight_g": 4.0,
        "development": "Ногти растут.",
        "tips": "Вода 1.5л.",
        "analyses": "Скрининг.",
        "checklist": ["Скрининг"],
    },
    11: {
        "size": "Лайм",
        "length_cm": 4.1,
        "weight_g": 7.0,
        "development": "Половые органы.",
        "tips": "Токсикоз уходит.",
        "analyses": "Скрининг.",
        "checklist": ["Скрининг"],
    },
    12: {
        "size": "Слива",
        "length_cm": 5.4,
        "weight_g": 14.0,
        "development": "Рефлексы.",
        "tips": "Конец 1 триместра!",
        "analyses": "Результаты.",
        "checklist": ["Результаты"],
    },
    13: {
        "size": "Персик",
        "length_cm": 7.4,
        "weight_g": 23.0,
        "development": "Кости твердеют.",
        "tips": "Золотой период.",
        "analyses": "",
        "checklist": ["Гардероб"],
    },
    14: {
        "size": "Лимон",
        "length_cm": 8.7,
        "weight_g": 43.0,
        "development": "Лануго.",
        "tips": "Йога.",
        "analyses": "",
        "checklist": ["Упражнения"],
    },
    15: {
        "size": "Яблоко",
        "length_cm": 10.1,
        "weight_g": 70.0,
        "development": "Чувствует свет.",
        "tips": "Спать на боку.",
        "analyses": "2-й скрининг.",
        "checklist": ["Подушка"],
    },
    16: {
        "size": "Авокадо",
        "length_cm": 11.6,
        "weight_g": 100.0,
        "development": "Мышцы лица.",
        "tips": "Шевеления!",
        "analyses": "",
        "checklist": ["Шевеления"],
    },
    17: {
        "size": "Груша",
        "length_cm": 13.0,
        "weight_g": 140.0,
        "development": "Подкожный жир.",
        "tips": "Омега-3.",
        "analyses": "",
        "checklist": ["Омега-3"],
    },
    18: {
        "size": "Перец",
        "length_cm": 14.2,
        "weight_g": 190.0,
        "development": "Слышит!",
        "tips": "Музыка.",
        "analyses": "УЗИ.",
        "checklist": ["УЗИ"],
    },
    19: {
        "size": "Манго",
        "length_cm": 15.3,
        "weight_g": 240.0,
        "development": "Смазка.",
        "tips": "Удобная обувь.",
        "analyses": "",
        "checklist": ["Обувь"],
    },
    20: {
        "size": "Банан",
        "length_cm": 16.4,
        "weight_g": 300.0,
        "development": "Экватор! Пол.",
        "tips": "Фотосессия.",
        "analyses": "УЗИ.",
        "checklist": ["УЗИ", "Фото"],
    },
    21: {
        "size": "Морковь",
        "length_cm": 26.7,
        "weight_g": 360.0,
        "development": "Координация.",
        "tips": "Разнообразие.",
        "analyses": "",
        "checklist": ["Рацион"],
    },
    22: {
        "size": "Кокос",
        "length_cm": 27.8,
        "weight_g": 430.0,
        "development": "Глаза.",
        "tips": "Ноги выше.",
        "analyses": "ГТТ.",
        "checklist": ["Глюкоза"],
    },
    23: {
        "size": "Грейпфрут",
        "length_cm": 28.9,
        "weight_g": 500.0,
        "development": "Сурфактант.",
        "tips": "Курсы.",
        "analyses": "",
        "checklist": ["Курсы"],
    },
    24: {
        "size": "Кукуруза",
        "length_cm": 30.0,
        "weight_g": 600.0,
        "development": "Ухо развито.",
        "tips": "Жизнеспособность.",
        "analyses": "ГТТ.",
        "checklist": ["ГТТ"],
    },
    25: {
        "size": "Брюква",
        "length_cm": 34.6,
        "weight_g": 660.0,
        "development": "Дыхание.",
        "tips": "Маленькие порции.",
        "analyses": "",
        "checklist": ["Порции"],
    },
    26: {
        "size": "Кабачок",
        "length_cm": 35.6,
        "weight_g": 760.0,
        "development": "Глаза открываются!",
        "tips": "Сумка в роддом.",
        "analyses": "",
        "checklist": ["Сумка"],
    },
    27: {
        "size": "Капуста",
        "length_cm": 36.6,
        "weight_g": 875.0,
        "development": "Извилины.",
        "tips": "Конец 2 триместра!",
        "analyses": "Антитела.",
        "checklist": ["Антитела"],
    },
    28: {
        "size": "Баклажан",
        "length_cm": 37.6,
        "weight_g": 1005.0,
        "development": "Сны.",
        "tips": "Шевеления 10/2ч.",
        "analyses": "3-й скрининг.",
        "checklist": ["Шевеления"],
    },
    29: {
        "size": "Тыква",
        "length_cm": 38.6,
        "weight_g": 1150.0,
        "development": "+200г/нед.",
        "tips": "Тренировочные схватки.",
        "analyses": "",
        "checklist": ["Схватки"],
    },
    30: {
        "size": "Капуста",
        "length_cm": 39.9,
        "weight_g": 1320.0,
        "development": "Кровь.",
        "tips": "Декрет.",
        "analyses": "Обменная карта.",
        "checklist": ["Декрет"],
    },
    31: {
        "size": "Ананас",
        "length_cm": 41.1,
        "weight_g": 1500.0,
        "development": "Свет.",
        "tips": "Левый бок.",
        "analyses": "",
        "checklist": ["Детская"],
    },
    32: {
        "size": "Дыня",
        "length_cm": 42.4,
        "weight_g": 1700.0,
        "development": "Кожа.",
        "tips": "3-е УЗИ.",
        "analyses": "УЗИ, КТГ.",
        "checklist": ["УЗИ", "КТГ"],
    },
    33: {
        "size": "Ананас",
        "length_cm": 43.7,
        "weight_g": 1920.0,
        "development": "Череп.",
        "tips": "Сумка.",
        "analyses": "",
        "checklist": ["Сумка"],
    },
    34: {
        "size": "Тыква",
        "length_cm": 45.0,
        "weight_g": 2150.0,
        "development": "Лёгкие.",
        "tips": "Врач 2 нед.",
        "analyses": "",
        "checklist": ["План родов"],
    },
    35: {
        "size": "Кокос",
        "length_cm": 46.2,
        "weight_g": 2380.0,
        "development": "Почки.",
        "tips": "Признаки родов.",
        "analyses": "Стрептококк.",
        "checklist": ["Признаки"],
    },
    36: {
        "size": "Папайя",
        "length_cm": 47.4,
        "weight_g": 2620.0,
        "development": "Лануго уходит.",
        "tips": "Еженедельно.",
        "analyses": "КТГ.",
        "checklist": ["Визиты"],
    },
    37: {
        "size": "Ревень",
        "length_cm": 48.6,
        "weight_g": 2860.0,
        "development": "Доношенный!",
        "tips": "Наготове.",
        "analyses": "КТГ.",
        "checklist": ["Сумка"],
    },
    38: {
        "size": "Тыква",
        "length_cm": 49.8,
        "weight_g": 3080.0,
        "development": "Меконий.",
        "tips": "Отдых.",
        "analyses": "КТГ.",
        "checklist": ["Отдых"],
    },
    39: {
        "size": "Арбуз",
        "length_cm": 50.7,
        "weight_g": 3290.0,
        "development": "Антитела.",
        "tips": "Предвестники.",
        "analyses": "КТГ.",
        "checklist": ["Предвестники"],
    },
    40: {
        "size": "Арбуз",
        "length_cm": 51.2,
        "weight_g": 3460.0,
        "development": "ПДР! 3-3.6кг.",
        "tips": "Не волнуйтесь.",
        "analyses": "КТГ, УЗИ.",
        "checklist": ["Рекомендации врача"],
    },
    41: {
        "size": "Арбуз",
        "length_cm": 51.5,
        "weight_g": 3600.0,
        "development": "Растёт.",
        "tips": "До 42 — норма.",
        "analyses": "КТГ 2-3 дня.",
        "checklist": ["Врач часто"],
    },
    42: {
        "size": "Арбуз",
        "length_cm": 52.0,
        "weight_g": 3700.0,
        "development": "Зрелый.",
        "tips": "Стимуляция.",
        "analyses": "Мониторинг.",
        "checklist": ["Готовность"],
    },
}


def get_week_info(week: int) -> WeekInfo | None:
    return WEEKS_DATA.get(week)
