# Generated by Django 6.0.3 on 2026-03-26 17:13

import django.utils.timezone
import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=media_app.models.media_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('gif', 'GIF'), ('doc', 'Документ')], default='image', max_length=10)),
                ('original_name', models.CharField(default='', max_length=255)),
                ('mime_type', models.CharField(default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Медиа-файл',
                'verbose_name_plural': 'Медиа-файлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
