# Generated by Django 6.0.3 on 2026-03-26 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('block_user', 'Блокировка'), ('resolve_report', 'Решение жалобы'), ('other', 'Другое')], max_length=20)),
                ('description', models.TextField(max_length=2000)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Пост'), ('comment', 'Комментарий'), ('user', 'Пользователь'), ('message', 'Сообщение')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('abuse', 'Оскорбление'), ('inappropriate', 'Неприемлемый'), ('other', 'Другое')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BabyBlog', max_length=200)),
                ('site_description', models.TextField(default='Сообщество для беременных', max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/site/')),
                ('primary_color', models.CharField(default='#e91e8c', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('accent_color', models.CharField(default='#ffc107', max_length=7)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('footer_text', models.TextField(blank=True, default='', max_length=500)),
                ('announcement', models.TextField(blank=True, default='', max_length=500)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('social_vk', models.URLField(blank=True, default='')),
                ('social_telegram', models.URLField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('max_posts_per_day', models.PositiveIntegerField(default=20)),
                ('auto_moderate_new_users', models.BooleanField(default=False)),
                ('banned_words', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
