# Generated by Django 6.0.3 on 2026-03-26 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('region', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('hospital_type', models.CharField(choices=[('public', 'Государственный'), ('private', 'Частный')], default='public', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('contacts', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.CharField(blank=True, default='', max_length=200)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating_avg', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('body', models.TextField(max_length=3000)),
                ('is_recommended', models.BooleanField(default=True)),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
