# Generated by Django 6.0.3 on 2026-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='media_app.mediafile'),
        ),
    ]
