# Generated by Django 6.0.3 on 2026-03-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalreview',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospitals.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalreview',
            unique_together={('hospital', 'author')},
        ),
    ]
